### PR TITLE
Change the log library from fimber to logging

### PR DESCRIPTION
**Pull request by ademar111190**
# Reasons to change from Fimber to Logging:
- Fimber IO has concurrency issues as reported here https://github.com/breez/c-breez/issues/588
- Fimber has not been receiving updates recently, even for bugs https://github.com/magillus/flutter-fimber/issues/135 with PR for fixing them available https://github.com/magillus/flutter-fimber/pull/137 
- Although I use (a lot) the LogCat integration offered by Fimber, most of the team does not and they are already used to the logging structure of the logging library (as we are using it on breeze mobile already)

# Drawbacks
- We lost the `SizeRollingFileTree`
  - I changed the logic to keep the last ten sessions as it seems a reasonable heuristic to me; Let me know your thoughts 
- LogCat integration as mentioned earlier

# How to test
- Everyone:
  - Goes to Developers -> three dots menu -> share logs
    - A zip file with the last 10 sessions (plus the current sessions) should be shared
- For devs:
  - Make sure the log shows on your console (debug flavors only)
 
# Please also review the SDK side of the changes
https://github.com/breez/breez-sdk/pull/505

Fixes https://github.com/breez/c-breez/issues/588
Fixes https://github.com/breez/c-breez/issues/587

### CODE REVIEW

**Review by ubbabeck — APPROVED** [review]
code looks good and tested 

works with logcat and vscode dev console and easy to filter.

exporting the logs also works.

**Comment by ademar111190** [comment]
* Just an addendum for clarity, we lost Logcat integrations but we still have basic functionalities working such as the output and filter messages by regex and by package

**Review by erdemyerebasmaz — APPROVED** [review]
LGTM!

Please re-trigger CI after breez-sdk changes are in place before merging, ty.

**Review by roeierez — COMMENTED** [review]
Looks good!
One think I am missing is the sdk logs.
Now that the sdk logs exposes `breezLogStream` shouldn't we use it here and log the records?

**Comment by ademar111190** [comment]
> Looks good! One think I am missing is the sdk logs. Now that the sdk logs exposes `breezLogStream` shouldn't we use it here and log the records?

Yes; I'm doing it here:
- https://github.com/breez/c-breez/pull/657/files#diff-e61eb31d013d12616f5532636a88cfa63631dda8f7829e5424e68542214d1608R58
- https://github.com/breez/c-breez/pull/657/files#diff-8229db30d0021c6aaf6196e316b5ca60b6d16a132c553f64380cdf512c6d506fR66-R85

**Pull request merged**
