### PR TITLE
Fix location of breez_sdkFFI.xcframework

### PR DESCRIPTION
**Pull request by cnixbtc**
In the iOS app, the _Breez Notification Service Extension_ needs the BreezSDK Swift bindings to be present. These consist of two parts:

1. `BreezSDK.swift`: the Swift language bindings for the underlying
1. `breez_sdkFFI.xcframework` binary which is built from the core Rust code base

We ship both of these as part of the `breez_sdk` Flutter package and then link them in the notification extension in Xcode like so:

Screenshot 2024-02-17 at 14 57 50

In the production version where we pull in the `breez_sdk` Flutter package from Git, these files are located in the `.pub_cache` directory where all other Flutter dependencies are installed. On my Mac this is:

```
~/.pub_cache/<...>/breez_sdk-flutter-<...>/ios/bindings-swift
```

You can verify by right clicking them in Xcode and select _Show in Finder_.

To enable a smooth development experience, when we use the `breez_sdk` Flutter plugin from a local build, these files should also link to the files part of the local Flutter plugin build. For the `BreezSDK.swift` file, this was already setup correctly. However, the `breez_sdkFFI.xcframework` was hardcoded to link to the local built always. Even in the production setup where it should actually link to the file in the `pub_cache`. This PR fixes this.

## Testing

To test the production setup, make sure you don't have these files in your local build of the `breez_sdk` Flutter plugin. For example, just remove the `breez-sdk/libs/sdk-flutter/ios/bindings-swift` directory.

Make sure the `pubspec.yaml` points to the production Flutter plugin from Git:

``` yaml
  breez_sdk:
    git:
      url: https://github.com/breez/breez-sdk-flutter
      ref: v0.3.1
```

Make sure c-breez builds correctly. Verify the location of `BreezSDK.swift` and `breez_sdkFFI.xcframework` in the notification extension by opening them in Finder.

Previously, this would've thrown a build error (_"...framework not found..."_) because Xcode was looking for the locally built version of `breez_sdkFFI.xcframework`.

Next, test the development setup. Build the flutter plugin locally (run `make ios` in `breez-sdk/libs/sdk-flutter`) and make sure the c-breez `pubspec.yaml` points to the local build:

``` yaml
  breez_sdk:
    path: ../breez-sdk/libs/sdk-flutter
```

Then, make sure c-breez builds correctly. Again, verify the location of the two files in the notification extension.

### CODE REVIEW

**Comment by erdemyerebasmaz** [comment]
@cnixbtc Could you rebase on top of main to see if this is compatible with: [Correct the Dart SDK range](https://github.com/breez/c-breez/commit/67fef716361cb5e5322685adfd22d052b19e4c04)

**Comment by cnixbtc** [comment]
Screenshot 2024-02-17 at 16 12 26


Getting some build errors now but this is probably just a mismatch of c-breez and the 0.3.0 release not having these changes yet I guess?

**Review by roeierez — APPROVED** [review]
LGTM

**Review by erdemyerebasmaz — APPROVED** [review]
LGTM

C-Breez is targeting main branch of breez-sdk and `ConnectRequest` issue you've encountered will be resolved with the next release of breez-sdk, likely on version 0.3.2.

**Pull request merged**
