### PR TITLE
Fix invoice CircularProgressIndicator artifacts

### LINKED ISSUE #832: Bad UI when creating an invoice
There is a thin double line in blue when waiting for an invoice to be created.
image

### PR DESCRIPTION
**Pull request by dangeross**
Fixes #832 

Screenshot_20240319_112053
Screenshot_20240319_112125

### CODE REVIEW

**Review by roeierez — APPROVED** [review]

**Comment by erdemyerebasmaz** [comment]
@dangeross Can you send me a video? I believe there's a slight difference on animation with this approach and previous implementation.

**Comment by dangeross** [comment]
https://github.com/breez/c-breez/assets/551697/3575a38e-490d-49c2-b455-4f7aebcf0632


https://github.com/breez/c-breez/assets/551697/673ac42a-3a1f-408d-9056-c70f9f06b227

**Comment by dangeross** [comment]
@erdemyerebasmaz can you clarify what needs changing?

**Review by erdemyerebasmaz — APPROVED** [review]

**Comment by erdemyerebasmaz** [comment]
> @erdemyerebasmaz can you clarify what needs changing?

I think I've confused it with synchronization spinner which has a visible ring underneath.

imageimage

We're good to merge this.

**Pull request merged**
