### PR TITLE
Change `connect` params

### PR DESCRIPTION
**Pull request by dangeross**
Use `ConnectRequest` when calling `connect`

SDK PR https://github.com/breez/breez-sdk/pull/790

### CODE REVIEW

**Comment by erdemyerebasmaz** [comment]
Hey @dangeross,
You'll need to manually target `savage-restore-only` branch of SDK on the CI workflow.
We haven't added an option to select an SDK branch from GitHub Actions view yet on C-Breez, you'll need to add a dummy commit as such: https://github.com/breez/c-breez/pull/762/commits/2bfb8cd9eabc85725d4dd64988817a86e0d481c3, which should be removed before merging.

**Comment by dangeross** [comment]
Thanks @erdemyerebasmaz. Do I need to leave it unmerged until the release that includes these changes?

**Comment by erdemyerebasmaz** [comment]
> Thanks @erdemyerebasmaz. Do I need to leave it unmerged until the release that includes these changes?

@dangeross My suggested approach would be triggering the CI again after 
- https://github.com/breez/breez-sdk/pull/790

gets merged.

**Comment by erdemyerebasmaz** [comment]
- Updated the [mock connect function](https://github.com/breez/c-breez/pull/779/files#diff-58008bdedede2f6d030a14da74dfc408cc368172ec026c291de969c70fbf7dfbR17) used on tests.

**Comment by erdemyerebasmaz** [comment]
Noticed this was missing when trying to build the app after merging this PR.
- Updated `connect` on notification extensions 029d24aff053741d94489821982e39a5d68c9bd6

**Comment by dangeross** [comment]
> Noticed this was missing when trying to build the app after merging this PR.
> 
> * Updated `connect` on notification extensions [029d24a](https://github.com/breez/c-breez/commit/029d24aff053741d94489821982e39a5d68c9bd6)

Thanks @erdemyerebasmaz!

**Pull request merged**
