### PR TITLE
Fee calculation and presentation

### PR DESCRIPTION
**Pull request by ademar111190**
Related https://github.com/breez/breez-sdk/pull/294

# How to test
- Close your channels
- Wait for the triangle showing unexpected funds appear at the top right of home page
  - It can take some hours
  - You can close the app and back later
- Go through the flow sending the sats to a btc wallet
- At the processing fee speed, choose one of the options
  - write down the fee and value you should receive at you address
- Confirm the transaction and wait for the sats appear at your wallet
  - It can take some hours
  - You can close the app and back later
- Check if the value you received and the fee paid is the same
  - It can be a few sats different from the forecasted
  - something like 2 sats of difference is expected.

### CODE REVIEW

**Review by ok300 — APPROVED** [review]
utACK

**Review by erdemyerebasmaz — COMMENTED** [review]
Please rebase or create a new PR on top of main.

**Comment by ademar111190** [comment]
I was about to test but the fee recommendation from mempool is 7satsvb for all; so I'll wait for at least one variation so I can double check the fee chooser is correct


https://github.com/breez/c-breez/assets/1225438/d8304dd8-6930-4b64-8daa-d177ab52575e

**Review by erdemyerebasmaz — APPROVED** [review]
LGTM

**Comment by ademar111190** [comment]
I just ran a test here (video attached) the difference from the fee showed and the fee realized was 2 satoshis:

<details>
<summary>Logs</summary>

```
[FeeOptionsBloc] {FINE} (2023-10-09T12:34:17.780976Z) : fetchFeeOptions recommendedFees:
fastestFee: 8,
halfHourFee: 6,
hourFee: 4.
[SweepBloc] {FINE} (2023-10-09T12:34:28.431894Z) : Sweep to address BC1QFGLJ5G6Z4RW3E7UL8JQTC2T4D4LZT4TAUN30UK using 8 fee vByte'

https://mempool.space/tx/a1241757839158c963ca875badc4a1d6d678aa9dd56d9ee3f094460b7af15946
Fee	874 sat$0.24
Fee rate 8.00 sat/vB
Dest 94 126 sats
```

</details>

<details>
<summary>Video</summary>


https://github.com/breez/c-breez/assets/1225438/22a58bf7-75f8-4fe6-8ad6-d7bc77b279d7


</details>

**Review by roeierez — APPROVED** [review]

**Pull request merged**
