### PR TITLE
Implement Android LNURL pay handler

### PR DESCRIPTION
**Pull request by dangeross**
There are still some outstanding issues to look at:

1. ~Service isn't triggered when the application is in the foreground~
2. ~Getting an exception after several (failed?) attempts~

```
E/AndroidRuntime(31300): FATAL EXCEPTION: main
E/AndroidRuntime(31300): Process: com.cBreez.client, PID: 31300
E/AndroidRuntime(31300): java.lang.RuntimeException: Unable to start service com.cBreez.client.BreezForegroundService@f929ce with Intent { cmp=com.cBreez.client/.BreezForegroundService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
E/AndroidRuntime(31300):        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5261)
E/AndroidRuntime(31300):        at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
E/AndroidRuntime(31300):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2447)
E/AndroidRuntime(31300):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31300):        at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(31300):        at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(31300):        at android.app.ActivityThread.main(ActivityThread.java:8762)
E/AndroidRuntime(31300):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31300):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
E/AndroidRuntime(31300):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
E/AndroidRuntime(31300): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Class.isInterface()' on a null object reference
E/AndroidRuntime(31300):        at java.lang.Class.isAssignableFrom(Class.java:824)
E/AndroidRuntime(31300):        at android.os.Parcel.readParcelableCreatorInternal(Parcel.java:4865)
E/AndroidRuntime(31300):        at android.os.Parcel.readParcelableInternal(Parcel.java:4778)
E/AndroidRuntime(31300):        at android.os.Parcel.readValue(Parcel.java:4544)
E/AndroidRuntime(31300):        at android.os.Parcel.readValue(Parcel.java:4324)
E/AndroidRuntime(31300):        at android.os.Parcel.-$$Nest$mreadValue(Unknown Source:0)
E/AndroidRuntime(31300):        at android.os.Parcel$LazyValue.apply(Parcel.java:4422)
E/AndroidRuntime(31300):        at android.os.Parcel$LazyValue.apply(Parcel.java:4381)
E/AndroidRuntime(31300):        at android.os.BaseBundle.getValueAt(BaseBundle.java:394)
E/AndroidRuntime(31300):        at android.os.BaseBundle.getValue(BaseBundle.java:374)
E/AndroidRuntime(31300):        at android.os.BaseBundle.getValue(BaseBundle.java:357)
E/AndroidRuntime(31300):        at android.os.BaseBundle.get(BaseBundle.java:696)
E/AndroidRuntime(31300):        at android.os.Bundle.getParcelable(Bundle.java:947)
E/AndroidRuntime(31300):        at android.content.Intent.getParcelableExtra(Intent.java:9558)
E/AndroidRuntime(31300):        at com.cBreez.client.BreezForegroundService.h(Unknown Source:13)
E/AndroidRuntime(31300):        at com.cBreez.client.BreezForegroundService.e(Unknown Source:3)
E/AndroidRuntime(31300):        at com.cBreez.client.BreezForegroundService.onStartCommand(Unknown Source:57)
E/AndroidRuntime(31300):        at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5243)
E/AndroidRuntime(31300):        ... 9 more
```

### CODE REVIEW

**Comment by roeierez** [comment]
> 1. Service isn't triggered when the application is in the foreground

That's probably because of this line: https://github.com/breez/c-breez/blob/main/android/app/src/main/kotlin/com/cBreez/client/BreezFcmService.kt#L30

**Comment by roeierez** [comment]
> > 1. Service isn't triggered when the application is in the foreground
> 
> That's probably because of this line: https://github.com/breez/c-breez/blob/main/android/app/src/main/kotlin/com/cBreez/client/BreezFcmService.kt#L30

@dangeross  Do you see any reason not to run it when the app is in the foreground?

**Comment by dangeross** [comment]
> That's probably because of this line: https://github.com/breez/c-breez/blob/main/android/app/src/main/kotlin/com/cBreez/client/BreezFcmService.kt#L30

Good catch

> @dangeross Do you see any reason not to run it when the app is in the foreground?

It should for LNURLpay to function properly, without relying on duplicate developer implementation

**Comment by roeierez** [comment]
> It should for LNURLpay to function properly, without relying on duplicate developer implementation

Let's remove that line then. The only drawback I see is that the user will see notifications for payment received/failed also when the app is in the foreground. Given the fact that in iOS we don't have any choice (extension must render a notification) I think we can live with that for now. We can disable that for android in the future.

**Review by roeierez — APPROVED** [review]
LGTM

**Comment by erdemyerebasmaz** [comment]
Thanks @dangeross, really appreciate the work you've done here !

**Comment by dangeross** [comment]
Thanks @erdemyerebasmaz 😊

**Pull request merged**
