### PR TITLE
Mnemonics enhancements

### PR DESCRIPTION
**Pull request by erdemyerebasmaz**
This PR addresses https://github.com/breez/c-breez/issues/474

- Remove MnemonicsVerificationHandler & VerifyMnemonicsDialog
  - Verify warning won't be shown after every payment and MnemonicsConfirmation page will be navigated directly from warning action
- Display MnemonicsPage in view mode if user has verified their mnemonics
- Persist verificationStatus
- Use new translated messages

### CODE REVIEW

**Comment by kingonly** [comment]
@erdemyerebasmaz can you please attach screenshots? Please include the Security & Backup screen.

**Review by roeierez — APPROVED** [review]

**Review by ubbabeck — COMMENTED** [review]
Tested it, but the screen still went black when verifying. Talked to Erdem and this was supposed to be fixed but a regression happened when rebasing.

**Comment by erdemyerebasmaz** [comment]
> @erdemyerebasmaz can you please attach screenshots? Please include the Security & Backup screen.

Yes, was resetting my accounts verification status. Will share a video on Slack.

> Tested it, but the screen still went black when verifying. Talked to Erdem and this was supposed to be fixed but a regression happened when rebasing.

Nice catch, I'll push the changes after testing.

**Review by ubbabeck — APPROVED** [review]
Tested the flow, everything seems good 👍

**Pull request merged**
